version: '3.7'

volumes:
    logs:
        driver: local
    dbVol:
        driver: local
services:
    slim:
        command: php -d variables_order=EGPCS -S 0.0.0.0:8080 -c /usr/local/etc/php/php.ini-development -t public 
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8081:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
            - ./php.ini-development/:/usr/local/etc/php/php.ini-development
        links:
            - database
    database:
        image: postgres
        container_name: database
        volumes:
         - dbVol:/var/lib/postgresql/data
        ports:
        - 5432:5432
        environment:
        - POSTGRES_DB:tcc_app
        - POSTGRES_USER:postgres
        - POSTGRES_PASSWORD:postgres
        - POSTGRES_HOST_AUTH_METHOD=trust